workspace:
  base: /ramdisk
  path: /mkinitramfs
pipeline:
  build:
    image: dvitali/pixelc-build-container:5
    commands:
      - git clone --depth 1 https://github.com/pixelc-linux/pixelc-mkinitramfs.sh mkinitramfs
      - cd mkinitramfs
      - wget $(curl https://api.github.com/repos/pixelc-linux/firmware-releases/releases/latest | jq -r '.assets[] | select(.name == "firmware_all.tar.gz") | .browser_download_url') -O firmware_all.tar.gz
      - "./mkinitramfs.sh -d mmcblk1p4 -o initramfs_system-mmcblk1p4.cpio"
      - "./mkinitramfs.sh -d mmcblk1p7 -o initramfs_data-mmcblk1p7.cpio"
  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: /ramdisk/mkinitramfs/mkinitramfs/*.cpio.gz
    when:
      event: tag
